---

# This config file is specific to running the standard Winston pipeline on
# a SGE managed cluster

###########################
## Output Specifications ##
###########################

# Directory to store all output files
output-dir: "/u/home/a/adityago/nobackup-eeskin2/winston38/"

# Directory to store intermediate files
working-dir: "/u/home/a/adityago/nobackup-eeskin2/winston38/"

# Directory to store logs
log-dir: "/u/home/a/adityago/nobackup-eeskin2/winston38/"

#############################
## Resource Specifications ##
#############################

#TODO: add config option for highp, rn its defuault is TRUE

# Number of times a task can start before being aborted
start-limit: "2"

# Max number of failed tasks that will be rerun; If more, analysis will be aborted
rerun-limit: "500"

# Number of regions to parallelize a sample
n-regions: "400"

# Max threads available for a task
n-threads: "1"

# Max memory available for each  task
#Memeory allocation coresponds to the following tasks:
#[fastq_prep, bwa, dedup_chri, dedup, base_recal, merge_recal, bqsr_hc_gvcf, merge_bams, check]
avail-memory: ["2G", "8G", "30G", "13G", "11G", "8G", "16G", "1G", "1G"]

# Max time allotted for a task (default 12 hours)
#Time allocation coresponds to the following tasks:  
#[fastq_prep, bwa, dedup_chri, dedup, base_recal, merge_recal, bqsr_hc_gvcf, merge_bams, check] 
avail-time: ["18:00:00", "12:00:00", "3:00:00", "01:00:00", "00:45:00", "00:30:00", "12:00:00", "18:00:00", "00:30:00"]

#Sequencing Platform
seq-plat: "ILLUMINA" 

# Unique identifier of output disk in output of "df" util, [NEED TO FIX THIS]
output-disk-identifier: "tmpfs"

# Analysis will halt if disk usage greater than or equal to this value
free-disk-threshold: "99"

# Number of samples actively analyzed on shared queue
shared-active-samples: "6"

# Number of samples actively analyzed on highp queue
highp-active-samples: "12"

#Run task on Highp [y or n]
#Highp allocation coresponds to the following tasks:
#[fastq_prep, bwa, dedup_chri, dedup, base_recal, merge_recal, bqsr_hc_gvcf, merge_bams, check]
highp-task: ["y", "y", "y", "y", "n", "n", "y", "y", "n"]

#Mail notify settings
mail-notify: ["y", "adihoffman2@gmail.com", "aditya.gorla@yahoo.com"]

##########################
## Program Dependencies ##
##########################

# Path to java 1.8.X executable 
java-dir: "/u/local/apps/java/jdk1.8.0_111/bin/java"

# Path to BWA executable
bin-bwa: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/lib/bwa/bwa-0.7.10/bwa"

# Path to GATK 3.7/3.8 jar
gatk-jar: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/lib/gatk/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"

# Path to Picard jar
picard-jar: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/lib/picard/picard.jar"

# Path to sambamba execuatble
# only use v0.6.6, new versions tend to unxexpectedly segfault on Xeon cores!
bin-sambamba:"/u/home/a/adityago/nobackup-eeskin2/winston_depn/lib/sambamba/sambamba_v0.6.6"

############################
## Reference Dependencies ##
############################

# Reference type
ref-type: "grch37"

# Full path to reference fasta file
ref-fasta: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/hg19bundle/hg19/hg19.fasta"

# Full path to reference dict file
ref-dict: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/hg19bundle/hg19/hg19.dict"

# Full path to reference dbsnp vcf file
dbsnp-vcf: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/hg19bundle/hg19/dbsnp_135.hg19.vcf"

# Full path to reference 1000g indels vcf file
1000g-indel-vcf: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/hg19bundle/hg19/1000G_phase1.indels.hg19.vcf"

# Full path to reference Mills and Devine indel vcf file
mills-devine-indel-vcf: "/u/home/a/adityago/nobackup-eeskin2/winston_depn/hg19bundle/hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"

...
